//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepsToUse
    {
        public int StepID { get; set; }
        public int Step1 { get; set; }
        public int Step2 { get; set; }
        public int Step3 { get; set; }
        public int Step4 { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
